version: "3.9"
services:
  db:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: slogging
  web:
    image: "app:latest"
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: "postgresql://postgres:mysecretpassword@db/slogging"
    depends_on:
      - db
