name: Scalable Logging Excercise
on: [push]
jobs:
  build_app:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      db_service:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Setup pipenv environment
        run: |
          python -m pip install --upgrade pipenv wheel
          pipenv --version

          pushd app
          pipenv install --dev

      - name: Run pre-commit checks
        run: |
          pip freeze
          pipenv run pre-commit run --all-files
