name: Scalable Logging Excercise
on: [push]
jobs:
  build_app:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Setup pipenv environment
        run: |
          python -m pip install --upgrade pipenv wheel
          pipenv --version
          pipenv install --dev
      - name: Run pre-commit checks
        run: |
          pipenv run pre-commit run --all-files
      - name: Build the app container
        run: |
          pushd app
          docker build -t app .
          popd
      - name: Bring up app and db containers
        run: |
          docker-compose up -d
      - name: Run unit tests
        run: |
          pipenv run pytest --reruns 5 --reruns-delay 5
      - name: Cleanup app and db containers
        run: |
          docker-compose down

  deploy_app:
    needs: build_app
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Terraform Install
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install terraform
          terraform --version
      - name: Terraform init and plan
        run: |
          cd terraform
          terraform init
          terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Terraform apply
        run: |
          cd terraform
          terraform apply --auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
